package doemais.views.screens.Item;

import doemais.BD.Acessa;
import java.awt.Point;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * @author DoeMais
 */
public class FrmAdicionarItem extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdicionarItem
     */
    public FrmAdicionarItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tudo = new javax.swing.JPanel();
        panel_titleBar = new javax.swing.JPanel();
        label_login = new javax.swing.JLabel();
        button_minimizar = new javax.swing.JButton();
        button_fechar = new javax.swing.JButton();
        textField_tipo = new javax.swing.JTextField();
        textField_nome = new javax.swing.JTextField();
        textField_tipoDeMedida = new javax.swing.JTextField();
        button_cancelar = new javax.swing.JButton();
        button_adicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DoeMais - Item");
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        panel_tudo.setBackground(new java.awt.Color(255, 255, 255));
        panel_tudo.setLayout(null);

        panel_titleBar.setBackground(new java.awt.Color(0, 29, 73));
        panel_titleBar.setFocusable(false);
        panel_titleBar.setPreferredSize(new java.awt.Dimension(40, 450));
        panel_titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_titleBarMouseDragged(evt);
            }
        });
        panel_titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_titleBarMousePressed(evt);
            }
        });
        panel_titleBar.setLayout(null);

        label_login.setFont(new java.awt.Font("David", 0, 18)); // NOI18N
        label_login.setForeground(new java.awt.Color(255, 255, 255));
        label_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_login.setText("DoeMais - Menu");
        label_login.setToolTipText("");
        label_login.setFocusable(false);
        label_login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_titleBar.add(label_login);
        label_login.setBounds(0, 0, 150, 40);

        button_minimizar.setBackground(new java.awt.Color(0, 29, 73));
        button_minimizar.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        button_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        button_minimizar.setText("-");
        button_minimizar.setBorder(null);
        button_minimizar.setFocusable(false);
        button_minimizar.setOpaque(false);
        button_minimizar.setRequestFocusEnabled(false);
        button_minimizar.addActionListener((e)-> {setExtendedState(ICONIFIED);});
        panel_titleBar.add(button_minimizar);
        button_minimizar.setBounds(320, 0, 40, 40);

        button_fechar.setBackground(new java.awt.Color(250, 65, 65));
        button_fechar.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        button_fechar.setForeground(new java.awt.Color(255, 255, 255));
        button_fechar.setText("X");
        button_fechar.setBorder(null);
        button_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_fechar.setFocusable(false);
        button_fechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_fechar.setRequestFocusEnabled(false);
        button_fechar.addActionListener((e)-> {doemais.views.screens.FrmMenu.habilitarItem();this.dispose();});
        panel_titleBar.add(button_fechar);
        button_fechar.setBounds(360, 0, 40, 40);

        panel_tudo.add(panel_titleBar);
        panel_titleBar.setBounds(0, 0, 400, 40);

        textField_tipo.setBackground(new java.awt.Color(219, 243, 255));
        textField_tipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textField_tipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_tipo.setUI(new doemais.views.UI.JTextFieldHintUI("Tipo", new java.awt.Color(166,166,166)));
        textField_tipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textField_tipo.setSelectionColor(new java.awt.Color(77, 141, 239));
        panel_tudo.add(textField_tipo);
        textField_tipo.setBounds(20, 70, 360, 30);

        textField_nome.setBackground(new java.awt.Color(219, 243, 255));
        textField_nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textField_nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_nome.setUI(new doemais.views.UI.JTextFieldHintUI("Nome", new java.awt.Color(166,166,166)));
        textField_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textField_nome.setSelectionColor(new java.awt.Color(77, 141, 239));
        panel_tudo.add(textField_nome);
        textField_nome.setBounds(20, 130, 360, 30);

        textField_tipoDeMedida.setBackground(new java.awt.Color(219, 243, 255));
        textField_tipoDeMedida.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textField_tipoDeMedida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_tipoDeMedida.setUI(new doemais.views.UI.JTextFieldHintUI("Tipo de medida", new java.awt.Color(166,166,166)));
        textField_tipoDeMedida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textField_tipoDeMedida.setSelectionColor(new java.awt.Color(77, 141, 239));
        panel_tudo.add(textField_tipoDeMedida);
        textField_tipoDeMedida.setBounds(20, 190, 360, 30);

        button_cancelar.setBackground(new java.awt.Color(250, 65, 65));
        button_cancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        button_cancelar.setText("Cancelar");
        button_cancelar.setBorder(null);
        button_cancelar.setBorderPainted(false);
        button_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_cancelar.setFocusPainted(false);
        button_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelarActionPerformed(evt);
            }
        });
        panel_tudo.add(button_cancelar);
        button_cancelar.setBounds(20, 250, 100, 30);

        button_adicionar.setBackground(new java.awt.Color(11, 26, 51));
        button_adicionar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        button_adicionar.setForeground(new java.awt.Color(255, 255, 255));
        button_adicionar.setText("Adicionar");
        button_adicionar.setBorder(null);
        button_adicionar.setBorderPainted(false);
        button_adicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_adicionar.setFocusPainted(false);
        button_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_adicionarActionPerformed(evt);
            }
        });
        panel_tudo.add(button_adicionar);
        button_adicionar.setBounds(280, 250, 100, 30);

        getContentPane().add(panel_tudo, "card2");

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_titleBarMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_panel_titleBarMouseDragged

    private void panel_titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_titleBarMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_panel_titleBarMousePressed

    private void button_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_adicionarActionPerformed
        // Adicionar Item
        if (textField_nome.getText().trim().isEmpty()
                || textField_tipo.getText().trim().isEmpty()
                || textField_tipoDeMedida.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "É necessário preencher todos os campos", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            //get data
            String nome = textField_nome.getText().replace("  ", " ");
            String tipo = textField_tipo.getText().replace("  ", " ");
            String tipoMedida = textField_tipoDeMedida.getText().replace("  ", " ");
            //set data in database
            String comando = "INSERT INTO [dbo].[tblItemPreCadastro] "
                    + "([ItemNome] "
                    + ",[ItemTipo] "
                    + ",[ItemTipoMedida] "
                    + ",[Ativo]) "
                    + "VALUES "
                    + "('" + (nome.length() <= 30 ? nome : nome.substring(0, 30)) + "' "
                    + ",'" + (tipo.length() <= 20 ? tipo : tipo.substring(0, 20)) + "' "
                    + ",'" + (tipoMedida.length() <= 25 ? tipoMedida : tipoMedida.substring(0, 25)) + "' "
                    + ",1)";
            Acessa bd = new Acessa();
            bd.entBanco();
            try {
                int sucesso = bd.stmt.executeUpdate(comando);
                if (sucesso > 0) {
                    JOptionPane.showMessageDialog(null, "Item cadastrado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao cadastrar item", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException sqle) {
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar item", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            button_cancelar.doClick();
        }
    }//GEN-LAST:event_button_adicionarActionPerformed

    private void button_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelarActionPerformed
        //
        doemais.views.screens.FrmMenu.habilitarItem();
        this.dispose();
    }//GEN-LAST:event_button_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdicionarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdicionarItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_adicionar;
    private javax.swing.JButton button_cancelar;
    private javax.swing.JButton button_fechar;
    private javax.swing.JButton button_minimizar;
    private javax.swing.JLabel label_login;
    private javax.swing.JPanel panel_titleBar;
    private javax.swing.JPanel panel_tudo;
    private javax.swing.JTextField textField_nome;
    private javax.swing.JTextField textField_tipo;
    private javax.swing.JTextField textField_tipoDeMedida;
    // End of variables declaration//GEN-END:variables

    private Point point = new Point();
}
