package doemais.views;

import doemais.BD.Acessa;
import java.awt.Point;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DoeMais
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tudo = new javax.swing.JPanel();
        panel_titleBar = new javax.swing.JPanel();
        label_login = new javax.swing.JLabel();
        button_minimizar = new javax.swing.JButton();
        button_fechar = new javax.swing.JButton();
        panel_fundoLateral = new javax.swing.JPanel();
        panel_lateralSuperior = new javax.swing.JPanel();
        panel_lateralInferior = new javax.swing.JPanel();
        label_logo = new javax.swing.JLabel();
        textField_user = new javax.swing.JTextField();
        textField_user.setUI(new doemais.views.UI.JTextFieldHintUI("Usuário", new java.awt.Color(166,166,166)));
        passwordField_senha = new doemais.views.UI.JPassWordFieldHint(new javax.swing.JPasswordField(), null, "Senha");
        button_entrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DoeMais- Login");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        panel_tudo.setBackground(new java.awt.Color(255, 255, 255));
        panel_tudo.setLayout(null);

        panel_titleBar.setBackground(new java.awt.Color(0, 29, 73));
        panel_titleBar.setFocusable(false);
        panel_titleBar.setPreferredSize(new java.awt.Dimension(40, 450));
        panel_titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_titleBarMouseDragged(evt);
            }
        });
        panel_titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_titleBarMousePressed(evt);
            }
        });
        panel_titleBar.setLayout(null);

        label_login.setFont(new java.awt.Font("David", 0, 18)); // NOI18N
        label_login.setForeground(new java.awt.Color(255, 255, 255));
        label_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_login.setText("DoeMais - Login");
        label_login.setToolTipText("");
        label_login.setFocusable(false);
        label_login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_titleBar.add(label_login);
        label_login.setBounds(0, 0, 150, 40);

        button_minimizar.setBackground(new java.awt.Color(255, 255, 255));
        button_minimizar.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        button_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        button_minimizar.setText("-");
        button_minimizar.setBorder(null);
        button_minimizar.setFocusable(false);
        button_minimizar.setOpaque(false);
        button_minimizar.setRequestFocusEnabled(false);
        button_minimizar.addActionListener((e)-> {setExtendedState(ICONIFIED);});
        panel_titleBar.add(button_minimizar);
        button_minimizar.setBounds(520, 0, 40, 40);

        button_fechar.setBackground(new java.awt.Color(250, 65, 65));
        button_fechar.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        button_fechar.setForeground(new java.awt.Color(255, 255, 255));
        button_fechar.setText("X");
        button_fechar.setBorder(null);
        button_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_fechar.setFocusable(false);
        button_fechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_fechar.setRequestFocusEnabled(false);
        button_fechar.addActionListener((e)-> {System.exit(0);});
        panel_titleBar.add(button_fechar);
        button_fechar.setBounds(560, 0, 40, 40);

        panel_tudo.add(panel_titleBar);
        panel_titleBar.setBounds(0, 0, 600, 40);

        panel_fundoLateral.setBackground(new java.awt.Color(0, 44, 112));
        panel_fundoLateral.setFocusable(false);
        panel_fundoLateral.setLayout(null);

        panel_lateralSuperior.setBackground(new java.awt.Color(255,255,255,10));

        javax.swing.GroupLayout panel_lateralSuperiorLayout = new javax.swing.GroupLayout(panel_lateralSuperior);
        panel_lateralSuperior.setLayout(panel_lateralSuperiorLayout);
        panel_lateralSuperiorLayout.setHorizontalGroup(
            panel_lateralSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        panel_lateralSuperiorLayout.setVerticalGroup(
            panel_lateralSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        panel_fundoLateral.add(panel_lateralSuperior);
        panel_lateralSuperior.setBounds(0, 0, 280, 136);

        panel_lateralInferior.setBackground(new java.awt.Color(255, 255, 255,10));

        javax.swing.GroupLayout panel_lateralInferiorLayout = new javax.swing.GroupLayout(panel_lateralInferior);
        panel_lateralInferior.setLayout(panel_lateralInferiorLayout);
        panel_lateralInferiorLayout.setHorizontalGroup(
            panel_lateralInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        panel_lateralInferiorLayout.setVerticalGroup(
            panel_lateralInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        panel_fundoLateral.add(panel_lateralInferior);
        panel_lateralInferior.setBounds(0, 274, 280, 136);

        label_logo.setForeground(new java.awt.Color(255, 255, 255));
        label_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_logo.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/doemais/views/imgs/DoeMais.png")).getImage().getScaledInstance(280, 137, java.awt.Image.SCALE_SMOOTH)));
        label_logo.setFocusable(false);
        panel_fundoLateral.add(label_logo);
        label_logo.setBounds(0, 136, 280, 137);

        panel_tudo.add(panel_fundoLateral);
        panel_fundoLateral.setBounds(0, 40, 280, 410);

        textField_user.setBackground(new java.awt.Color(219, 243, 255));
        textField_user.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textField_user.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(68, 68, 68), 2, true));
        textField_user.setCaretColor(new java.awt.Color(255, 255, 255));
        panel_tudo.add(textField_user);
        textField_user.setBounds(315, 180, 245, 35);

        passwordField_senha.setBackground(new java.awt.Color(219, 243, 255));
        passwordField_senha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passwordField_senha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(68, 68, 68), 2, true));
        passwordField_senha.setCaretColor(new java.awt.Color(255, 255, 255));
        panel_tudo.add(passwordField_senha);
        passwordField_senha.setBounds(315, 230, 245, 35);

        button_entrar.setBackground(new java.awt.Color(255, 87, 87));
        button_entrar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        button_entrar.setText("Entrar");
        button_entrar.setBorder(null);
        button_entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_entrar.setFocusPainted(false);
        button_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_entrarActionPerformed(evt);
            }
        });
        panel_tudo.add(button_entrar);
        button_entrar.setBounds(390, 270, 100, 35);

        getContentPane().add(panel_tudo, "Tudo");

        setSize(new java.awt.Dimension(600, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_titleBarMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_panel_titleBarMousePressed

    private void panel_titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_titleBarMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_panel_titleBarMouseDragged

    private void button_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_entrarActionPerformed
        // LOGIN

        if (textField_user.getText() == null || textField_user.getText().trim().equals("")
                || passwordField_senha.getText() == null || passwordField_senha.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha usuário e senha");
            return;
        }

        bd.entBanco();
        String comando = "SELECT COUNT(*), Adm FROM tblFuncionarioDoeMais "
                + "WHERE REPLACE(REPLACE(CPF, '.', ''), '-', '') LIKE '" + textField_user.getText().replace(".", "").replace("-", "")
                + "' AND Senha LIKE '" + passwordField_senha.getText() + "' "
                + "GROUP BY Adm";
        try {
            bd.RS = bd.stmt.executeQuery(comando);
            while (bd.RS.next()) {
                if ("1".equals(bd.RS.getString(1))) {
                    if ("0".equals(bd.RS.getString(2))) {
                        new doemais.DoeMais().MENU(false);
                    } else {
                        new doemais.DoeMais().MENU(true);
                    }
                    this.show(false);
                    return;
                }
            }
            JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos");
        } catch (SQLException ssql) {
            JOptionPane.showMessageDialog(null, "Erro ao se conectarao banco.");
        }catch (NullPointerException ne){
            
        }
    }//GEN-LAST:event_button_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_entrar;
    private javax.swing.JButton button_fechar;
    private javax.swing.JButton button_minimizar;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_logo;
    private javax.swing.JPanel panel_fundoLateral;
    private javax.swing.JPanel panel_lateralInferior;
    private javax.swing.JPanel panel_lateralSuperior;
    private javax.swing.JPanel panel_titleBar;
    private javax.swing.JPanel panel_tudo;
    private javax.swing.JPasswordField passwordField_senha;
    private javax.swing.JTextField textField_user;
    // End of variables declaration//GEN-END:variables

    private Point point = new Point();
    //
    Acessa bd = new Acessa();
}
