package doemais.views;

import java.awt.Point;


public class FrmMenu extends javax.swing.JFrame {

    
    public FrmMenu() {
        initComponents();
        
        card = (java.awt.CardLayout) panel_lateralEsquerdoCards.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tudo = new javax.swing.JPanel();
        panel_titleBar = new javax.swing.JPanel();
        label_login = new javax.swing.JLabel();
        button_minimizar = new javax.swing.JButton();
        button_fechar = new javax.swing.JButton();
        panel_fundoLateral = new javax.swing.JPanel();
        panel_lateralMenu = new javax.swing.JPanel();
        button_addItens = new javax.swing.JButton();
        button_funcionarios = new javax.swing.JButton();
        button_instituicoes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panel_lateralEsquerdoCards = new javax.swing.JPanel();
        panel_itens = new javax.swing.JPanel();
        panel_funcionarios = new javax.swing.JPanel();
        panel_instituicoes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doe Mais - Menu");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        panel_tudo.setLayout(null);

        panel_titleBar.setBackground(new java.awt.Color(0, 29, 73));
        panel_titleBar.setFocusable(false);
        panel_titleBar.setPreferredSize(new java.awt.Dimension(40, 450));
        panel_titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_titleBarMouseDragged(evt);
            }
        });
        panel_titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_titleBarMousePressed(evt);
            }
        });
        panel_titleBar.setLayout(null);

        label_login.setFont(new java.awt.Font("David", 0, 18)); // NOI18N
        label_login.setForeground(new java.awt.Color(255, 255, 255));
        label_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_login.setText("DoeMais - Login");
        label_login.setToolTipText("");
        label_login.setFocusable(false);
        label_login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel_titleBar.add(label_login);
        label_login.setBounds(0, 0, 150, 40);

        button_minimizar.setBackground(new java.awt.Color(255, 255, 255));
        button_minimizar.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        button_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        button_minimizar.setText("-");
        button_minimizar.setBorder(null);
        button_minimizar.setFocusable(false);
        button_minimizar.setOpaque(false);
        button_minimizar.setRequestFocusEnabled(false);
        button_minimizar.addActionListener((e)-> {setExtendedState(ICONIFIED);});
        panel_titleBar.add(button_minimizar);
        button_minimizar.setBounds(520, 0, 40, 40);

        button_fechar.setBackground(new java.awt.Color(250, 65, 65));
        button_fechar.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        button_fechar.setForeground(new java.awt.Color(255, 255, 255));
        button_fechar.setText("X");
        button_fechar.setBorder(null);
        button_fechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button_fechar.setFocusable(false);
        button_fechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_fechar.setRequestFocusEnabled(false);
        button_fechar.addActionListener((e)-> {System.exit(0);});
        panel_titleBar.add(button_fechar);
        button_fechar.setBounds(560, 0, 40, 40);

        panel_tudo.add(panel_titleBar);
        panel_titleBar.setBounds(0, 0, 600, 40);

        panel_fundoLateral.setBackground(new java.awt.Color(0, 44, 112));
        panel_fundoLateral.setLayout(null);

        panel_lateralMenu.setBackground(new java.awt.Color(255,255,255,10));
        panel_lateralMenu.setLayout(null);

        button_addItens.setBackground(new java.awt.Color(11, 26, 51));
        button_addItens.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        button_addItens.setForeground(new java.awt.Color(255, 255, 255));
        button_addItens.setText("Add Itens");
        button_addItens.setBorder(null);
        button_addItens.setFocusPainted(false);
        button_addItens.addActionListener((e) -> {card.show(panel_lateralEsquerdoCards, "itens");});
        panel_lateralMenu.add(button_addItens);
        button_addItens.setBounds(40, 23, 180, 35);

        button_funcionarios.setBackground(new java.awt.Color(11, 26, 51));
        button_funcionarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        button_funcionarios.setForeground(new java.awt.Color(255, 255, 255));
        button_funcionarios.setText("Funcionários");
        button_funcionarios.setBorder(null);
        button_funcionarios.setFocusPainted(false);
        button_funcionarios.addActionListener((e)->{card.show(panel_lateralEsquerdoCards, "func");});
        panel_lateralMenu.add(button_funcionarios);
        button_funcionarios.setBounds(40, 81, 180, 35);

        button_instituicoes.setBackground(new java.awt.Color(11, 26, 51));
        button_instituicoes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        button_instituicoes.setForeground(new java.awt.Color(255, 255, 255));
        button_instituicoes.setText("Instituições");
        button_instituicoes.setBorder(null);
        button_instituicoes.setFocusPainted(false);
        button_instituicoes.addActionListener((e)->{card.show(panel_lateralEsquerdoCards, "insti");});
        panel_lateralMenu.add(button_instituicoes);
        button_instituicoes.setBounds(40, 139, 180, 35);

        panel_fundoLateral.add(panel_lateralMenu);
        panel_lateralMenu.setBounds(0, 205, 280, 205);

        jLabel1.setIcon(new javax.swing.ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/doemais/views/imgs/DoeMais.png")).getImage().getScaledInstance(300, 180, java.awt.Image.SCALE_SMOOTH)));
        panel_fundoLateral.add(jLabel1);
        jLabel1.setBounds(0, 0, 280, 205);

        panel_tudo.add(panel_fundoLateral);
        panel_fundoLateral.setBounds(0, 40, 280, 410);

        panel_lateralEsquerdoCards.setLayout(new java.awt.CardLayout());

        panel_itens.setBackground(new java.awt.Color(204, 204, 255));
        panel_lateralEsquerdoCards.add(panel_itens, "itens");

        panel_funcionarios.setBackground(new java.awt.Color(153, 0, 0));
        panel_lateralEsquerdoCards.add(panel_funcionarios, "func");

        panel_instituicoes.setBackground(new java.awt.Color(51, 255, 51));
        panel_lateralEsquerdoCards.add(panel_instituicoes, "insti");

        panel_tudo.add(panel_lateralEsquerdoCards);
        panel_lateralEsquerdoCards.setBounds(280, 40, 320, 410);

        getContentPane().add(panel_tudo, "card2");

        setSize(new java.awt.Dimension(600, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_titleBarMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() -  point.y);
    }//GEN-LAST:event_panel_titleBarMouseDragged

    private void panel_titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_titleBarMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_panel_titleBarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_addItens;
    private javax.swing.JButton button_fechar;
    private javax.swing.JButton button_funcionarios;
    private javax.swing.JButton button_instituicoes;
    private javax.swing.JButton button_minimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_login;
    private javax.swing.JPanel panel_funcionarios;
    private javax.swing.JPanel panel_fundoLateral;
    private javax.swing.JPanel panel_instituicoes;
    private javax.swing.JPanel panel_itens;
    private javax.swing.JPanel panel_lateralEsquerdoCards;
    private javax.swing.JPanel panel_lateralMenu;
    private javax.swing.JPanel panel_titleBar;
    private javax.swing.JPanel panel_tudo;
    // End of variables declaration//GEN-END:variables

private Point point = new Point();
private java.awt.CardLayout card;
}
